Decorators
David-Lanzz/OOP-School-Library pull request #2
Opened 2023-05-23 17:13 UTC by David-Lanzz

# Hello Reviewer!!!
![images](https://github.com/David-Lanzz/OOP-School-Library/assets/111298026/5e912a55-fc37-495b-9669-460683203ea9)

## I have completed the assigned tasks to me and below is a summary of my work
- Correct use of git flow
- No linter errors
- Using decorators and creating new classes
- Correct implementation of "super"
- Task completion
## If you have any issues, contributions, or suggestions, please let me know via the comment section of this PR

2023-05-23 17:47 UTC, KDlamini requested changes
### Hi @David-Lanzz  🙋‍♀️,  

Great work so far! 💯 
You have done a great job decorating your classes. 🎊 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  `Person` class inherits from the `Nameable` class.
✔️  The `Decorator` class inherits from Namable.
✔️  The `CapitalizeDecorator` and `TrimmerDecorator` classes inherit from `Decorator`.

## Required Changes ♻️

- Kindly add a more detailed and descriptive project description on the README. Explain the features of the project.

![image](https://github.com/David-Lanzz/OOP-School-Library/assets/38088818/986db3ec-8097-4f46-9557-83e2b6a4d49a)
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 17:47 UTC, KDlamini commented on classes/nameable.rb
> +end
[OPTIONAL] You can improve the error message by including the class from which the error originates in the message.

Like this.
```ruby
class Nameable
    def correct_name
        raise NotImplementedError, "#{self.class} has not implemented method '#{__method__}'"
    end
end
```

2023-05-23 17:47 UTC, KDlamini commented on classes/capitalize.rb
> +end
When I run tests on your project I get this error.

![image](https://github.com/David-Lanzz/OOP-School-Library/assets/38088818/cc65c8aa-54ac-4e25-b026-1b72937ab780)

- This is because the method `upcase` should be used on a string and on your case `nameable` does not return a string. Remember to call `correct_name` on the variable to return the correct name.
- Also the project requirement states that you should only capitalize the first word, `upcase` will make the entire string uppercase.

Your method should look like this.
```ruby
    def correct_name
      @nameable.correct_name.capitalize
    end
```

2023-05-23 17:47 UTC, KDlamini commented on classes/trimmer.rb
> +end
The same thing applies here.

![image](https://github.com/David-Lanzz/OOP-School-Library/assets/38088818/5b6952fd-1227-4efb-8b04-8011faa97d46)

- Because you are not using `correct_name` on the `nameable` variable trying to trim an undefined variable throws an error.

Try:
```ruby
  def correct_name
    @nameable.correct_name[0..9]
  end
```

2023-05-23 17:47 UTC, KDlamini requested changes
### Hi @David-Lanzz  🙋‍♀️,  

Great work so far! 💯 
You have done a great job decorating your classes. 🎊 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  `Person` class inherits from the `Nameable` class.
✔️  The `Decorator` class inherits from Namable.
✔️  The `CapitalizeDecorator` and `TrimmerDecorator` classes inherit from `Decorator`.

## Required Changes ♻️

- Kindly add a more detailed and descriptive project description on the README. Explain the features of the project.

![image](https://github.com/David-Lanzz/OOP-School-Library/assets/38088818/986db3ec-8097-4f46-9557-83e2b6a4d49a)
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 17:47 UTC, KDlamini requested changes
### Hi @David-Lanzz  🙋‍♀️,  

Great work so far! 💯 
You have done a great job decorating your classes. 🎊 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  `Person` class inherits from the `Nameable` class.
✔️  The `Decorator` class inherits from Namable.
✔️  The `CapitalizeDecorator` and `TrimmerDecorator` classes inherit from `Decorator`.

## Required Changes ♻️

- Kindly add a more detailed and descriptive project description on the README. Explain the features of the project.

![image](https://github.com/David-Lanzz/OOP-School-Library/assets/38088818/986db3ec-8097-4f46-9557-83e2b6a4d49a)
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 17:47 UTC, KDlamini requested changes
### Hi @David-Lanzz  🙋‍♀️,  

Great work so far! 💯 
You have done a great job decorating your classes. 🎊 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  `Person` class inherits from the `Nameable` class.
✔️  The `Decorator` class inherits from Namable.
✔️  The `CapitalizeDecorator` and `TrimmerDecorator` classes inherit from `Decorator`.

## Required Changes ♻️

- Kindly add a more detailed and descriptive project description on the README. Explain the features of the project.

![image](https://github.com/David-Lanzz/OOP-School-Library/assets/38088818/986db3ec-8097-4f46-9557-83e2b6a4d49a)
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 09:47 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @David-Lanzz,

✔️ Implementation of trimmer

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 09:47 UTC, TedLivist commented on classes/capitalize.rb
> +    super.upcase
- [ ] This should be `capitalize`, not `upcase` as pointed out by the previous reviewer

2023-05-24 10:05 UTC, osamaashraf6 approved these changes
Hi @David-Lanzz 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![MinionsGIF (2)](https://github.com/David-Lanzz/OOP-School-Library/assets/83360636/b92e83be-5702-463c-b341-5fe2408ad6d0)

## Highlights🎉🎉

- [x] No linter errors present💯
- [x] The PR has a proper title and a descriptive body 👍
- [x] Good following GitFlow 👍

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 15:03 UTC, merged